// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = { 
/**
 * Whether to copy the login shell environment to the app's environment.
 */
copy_shell_env: boolean, };
