// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AIBinarySource = { "type": "url", "data": string } | { "type": "base64", "data": string };
