// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIBinarySource } from "./AIBinarySource";

export type AIBinary = { contentType: string, source: AIBinarySource, name: string | null, };
