// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIMessageContent } from "./AIMessageContent";
import type { AIMessageRole } from "./AIMessageRole";

export type AIMessage = { role: AIMessageRole, content: AIMessageContent, };
