// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIBinary } from "./AIBinary";
import type { AIToolCall } from "./AIToolCall";
import type { AIToolResponse } from "./AIToolResponse";

export type AIMessageContentPart = { "type": "text", "data": string } | { "type": "binary", "data": AIBinary } | { "type": "toolCall", "data": AIToolCall } | { "type": "toolResponse", "data": AIToolResponse } | { "type": "thoughtSignature", "data": string };
