// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockErrorData } from "./BlockErrorData";
import type { BlockFinishedData } from "./BlockFinishedData";

/**
 * Block lifecycle events
 *
 * Indicates state transitions during block execution.
 */
export type BlockLifecycleEvent = { "type": "started", "data": string } | { "type": "finished", "data": BlockFinishedData } | { "type": "cancelled" } | { "type": "error", "data": BlockErrorData } | { "type": "paused" };
