// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockLifecycleEvent } from "./BlockLifecycleEvent";
import type { JsonValue } from "./serde_json/JsonValue";

export type BlockOutput = { stdout: string | null, stderr: string | null, lifecycle: BlockLifecycleEvent | null, binary: Array<number> | null, object: JsonValue | null, };
