// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fix } from "./Fix";
import type { Severity } from "./Severity";

/**
 * ShellCheck output format
 *
 * Reference https://github.com/koalaman/shellcheck/blob/master/src/ShellCheck/Formatter/JSON.hs
 *
 * ShellCheck uses the arbitrary precision Integer type in Haskell instead of
 * the 32/64 bit fixed width Int for their integers, but u32 should be enough.
 */
export type Comment = { file: string, line: number, endLine: number, column: number, endColumn: number, level: Severity, code: number, message: string, fix: Fix | null, };
