// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fix } from "./Fix";
import type { Severity } from "./Severity";

export type Diagnostic = { file: string, line: bigint, endLine: bigint, column: bigint, endColumn: bigint, level: Severity, code: bigint, message: string, fix: Fix, };
