// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DirEntry = { name: string, is_dir: boolean, path: string, lastmod: { secs_since_epoch: number, nanos_since_epoch: number } | null, };
