// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Replacement } from "./Replacement";

export type Fix = { replacements: Array<Replacement>, };
