// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpResponse = { status: number, statusText: string, statusSuccess: boolean, headers: { [key in string]?: string }, duration: number, time: string, body: string, };
