// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionEvent } from "./SessionEvent";
import type { SessionInfo } from "./SessionInfo";

/**
 * Events broadcast to the LLM Tools window.
 */
export type LLMToolsEvent = { "type": "sessionCreated", info: SessionInfo, } | { "type": "sessionDestroyed", session_id: string, } | { "type": "sessionEvent", session_id: string, event: SessionEvent, };
