// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelSelection = { "type": "atuinHub", "data": { model: string, uri: string | null, } } | { "type": "claude", "data": { model: string, } } | { "type": "openAI", "data": { model: string, uri: string | null, } } | { "type": "ollama", "data": { model: string, uri: string | null, } };
