// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrometheusQueryResult } from "./PrometheusQueryResult";

/**
 * Output structure for Prometheus blocks that implements BlockExecutionOutput
 * for template access to query results.
 */
export type PrometheusBlockOutput = { 
/**
 * All query results from the Prometheus execution
 */
results: Array<PrometheusQueryResult>, 
/**
 * Total number of series across all results
 */
totalSeries: number, };
