// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrometheusTimeRange } from "./PrometheusTimeRange";

export type PrometheusQueryResult = { 
/**
 * Columnar data for uPlot: [timestamps, series1_values, series2_values, ...]
 * Timestamps are in seconds (Unix epoch)
 */
data: Array<Array<number>>, 
/**
 * Series names in order (index i corresponds to data[i+1])
 */
seriesNames: Array<string>, queryExecuted: string, timeRange: PrometheusTimeRange, };
