// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptOptionColor } from "./PromptOptionColor";
import type { PromptOptionVariant } from "./PromptOptionVariant";

/**
 * A button option in a client prompt dialog
 */
export type PromptOption = { label: string, value: string, variant: PromptOptionVariant | null, color: PromptOptionColor | null, };
