// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsertionPoint } from "./InsertionPoint";

export type Replacement = { line: number, endLine: number, column: number, endColumn: number, insertionPoint: InsertionPoint, precedence: number, replacement: string, };
