// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropdownOption } from "./DropdownOption";

export type ResolvedDropdownState = { options: Array<DropdownOption>, };
