// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RustOfflineRunbookFile = { id: string, name: string, content: any[], created: { secs_since_epoch: number, nanos_since_epoch: number } | null, updated: { secs_since_epoch: number, nanos_since_epoch: number } | null, };
