// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputLine } from "./OutputLine";

export type ScriptExecutionOutput = { exitCode: number | null, output: Array<OutputLine>, };
