// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary information about an active session for the LLM Tools window.
 */
export type SessionInfo = { id: string, runbookId: string, kind: string, };
