// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIMessage } from "./AIMessage";
import type { AIToolCall } from "./AIToolCall";
import type { State } from "./State";

/**
 * Events emitted by the session to the frontend.
 */
export type SessionEvent = { "type": "stateChanged", state: State, } | { "type": "streamStarted" } | { "type": "chunk", content: string, } | { "type": "responseComplete" } | { "type": "toolsRequested", calls: Array<AIToolCall>, } | { "type": "error", message: string, } | { "type": "cancelled" } | { "type": "history", messages: Array<AIMessage>, pendingToolCalls: Array<AIToolCall>, };
