// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChargeTarget } from "./ChargeTarget";
import type { ModelSelection } from "./ModelSelection";

export type SessionConfig = { model: ModelSelection, desktopUsername: string, chargeTarget: ChargeTarget, };
