// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockInfo } from "./BlockInfo";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The type of the session, which determines the behavior of the session.
 * Any data necessary for the session should be included here.
 */
export type SessionKind = { "type": "assistantChat", "data": { runbook_id: string, block_infos: Array<BlockInfo>, } } | { "type": "inlineBlockGeneration", "data": { runbook_id: string, block_infos: Array<BlockInfo>, current_document: JsonValue, 
/**
 * The ID of the block after which to insert the new blocks;
 * this is the block where the user pressed Cmd/Ctrl+Enter.
 */
insert_after: string, } };
