// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlBlockExecutionResult } from "./SqlBlockExecutionResult";

/**
 * Output structure for SQL blocks that implements BlockExecutionOutput
 * for template access to query results.
 */
export type SqlBlockOutput = { 
/**
 * All results from the SQL execution (supports multiple statements)
 */
results: Array<SqlBlockExecutionResult>, 
/**
 * Total execution duration in seconds
 */
totalDuration: number, };
