// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The discrete states of the agent FSM.
 */
export type State = { "type": "idle" } | { "type": "sending" } | { "type": "streaming" } | { "type": "pendingTools" };
