// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

export type WorkspaceState = { id: string, name: string, root: string, entries: Array<DirEntry>, runbooks: Record<string, WorkspaceRunbook>, };
