// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";
import type { WorkspaceRunbook } from "./WorkspaceRunbook";

export type WorkspaceState = { id: string, name: string, entries: Array<DirEntry>, runbooks: { [key in string]?: WorkspaceRunbook }, };
