// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceError } from "./WorkspaceError";
import type { WorkspaceState } from "./WorkspaceState";

export type WorkspaceEvent = { "type": "State", "data": WorkspaceState } | { "type": "Error", "data": WorkspaceError } | { "type": "OtherMessage", "data": string };
