// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceState } from "./WorkspaceState";

export type WorkspaceEvent = { "InitialState": WorkspaceState } | { "OtherMessage": string };
