// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";
import type { WorkspaceRunbook } from "./WorkspaceRunbook";

export type WorkspaceStateChange = { "type": "WorkspaceNameChanged", "data": string } | { "type": "DirEntriesChanged", "data": Array<DirEntry> } | { "type": "RunbookAdded", "data": WorkspaceRunbook } | { "type": "RunbookUpdated", "data": WorkspaceRunbook } | { "type": "RunbookDeleted", "data": string };
