// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceRunbook = { id: string, name: string, version: number, path: string, lastmod: { secs_since_epoch: number, nanos_since_epoch: number } | null, };
