// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceError = { "type": "WorkspaceReadError", "data": [string, string] } | { "type": "WorkspaceCreateError", "data": [string, string] } | { "type": "WorkspaceNotWatched", "data": string } | { "type": "WorkspaceAlreadyWatched", "data": string } | { "type": "RunbookSaveError", "data": [string, string] } | { "type": "WorkspaceRenameError", "data": [string, string] } | { "type": "WatchError", "data": [string, string] };
