// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for block error lifecycle event
 */
export type BlockErrorData = { message: string, };
