// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result from a client prompt interaction
 */
export type ClientPromptResult = { 
/**
 * The value of the button that was clicked
 */
button: string, 
/**
 * The value entered in an input field, if any
 */
value: string | null, };
