// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptIcon } from "./PromptIcon";
import type { PromptInput } from "./PromptInput";
import type { PromptOption } from "./PromptOption";

export type ClientPrompt = { title: string, prompt: string, icon: PromptIcon | null, input: PromptInput | null, options: Array<PromptOption>, };
