// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientPrompt } from "./ClientPrompt";
import type { ResolvedContext } from "./ResolvedContext";
import type { StreamingBlockOutput } from "./StreamingBlockOutput";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Messages sent from the runtime to the client application
 *
 * These messages communicate execution state, output, and context updates
 * to the desktop application frontend.
 */
export type DocumentBridgeMessage = { "type": "blockContextUpdate", "data": { blockId: string, context: ResolvedContext, } } | { "type": "blockStateChanged", "data": { blockId: string, state: JsonValue, } } | { "type": "blockExecutionOutputChanged", "data": { blockId: string, } } | { "type": "blockOutput", "data": { blockId: string, output: StreamingBlockOutput, } } | { "type": "clientPrompt", "data": { executionId: string, promptId: string, prompt: ClientPrompt, } };
