// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrometheusSeries = { type: string, showSymbol: boolean, name: string, data: Array<[number, number]>, };
