// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrometheusSeries } from "./PrometheusSeries";
import type { PrometheusTimeRange } from "./PrometheusTimeRange";

export type PrometheusQueryResult = { series: Array<PrometheusSeries>, queryExecuted: string, timeRange: PrometheusTimeRange, };
