// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about a PTY instance
 */
export type PtyMetadata = { 
/**
 * Unique PTY identifier
 */
pid: string, 
/**
 * Runbook ID this PTY belongs to
 */
runbook: string, 
/**
 * Block ID that created this PTY
 */
block: string, 
/**
 * Unix timestamp when PTY was created
 */
created_at: bigint, };
