// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PtyMetadata = { pid: string, runbook: string, block: string, created_at: bigint, };
