// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A struct representing the resolved context of a block.
 * Since it's built from a `ContextResolver`, it's a snapshot
 * of the final context based on the blocks above it.
 */
export type ResolvedContext = { variables: { [key in string]?: string }, cwd: string, envVars: { [key in string]?: string }, sshHost: string | null, };
