// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlQueryResult } from "./SqlQueryResult";
import type { SqlStatementResult } from "./SqlStatementResult";

export type SqlBlockExecutionResult = { "type": "Query", "data": SqlQueryResult } | { "type": "Statement", "data": SqlStatementResult };
