// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type SqlQueryResult = { columns: Array<string>, rows: Array<{ [key in string]?: JsonValue }>, rowsRead: number | null, bytesRead: number | null, duration: number, time: string, };
